<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\EventSubscriber\CommentNotificationSubscriber' shared autowired service.

include_once $this->targetDirs[3].'/src/EventSubscriber/CommentNotificationSubscriber.php';

return $this->privates['App\EventSubscriber\CommentNotificationSubscriber'] = new \App\EventSubscriber\CommentNotificationSubscriber(($this->services['swiftmailer.mailer.default'] ?? $this->load('getSwiftmailer_Mailer_DefaultService.php')), ($this->services['router'] ?? $this->getRouterService()), ($this->services['translator'] ?? $this->getTranslatorService()), 'anonymous@example.com');
