<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Command\ListUsersCommand' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/src/Command/ListUsersCommand.php';

$this->privates['App\Command\ListUsersCommand'] = $instance = new \App\Command\ListUsersCommand(($this->services['swiftmailer.mailer.default'] ?? $this->load('getSwiftmailer_Mailer_DefaultService.php')), 'anonymous@example.com', ($this->privates['App\Repository\UserRepository'] ?? $this->load('getUserRepositoryService.php')));

$instance->setName('app:list-users');

return $instance;
